#!/bin/sh

echo 'START REDIS';

/home/redis-2.6.17/src/redis-server --port 6381 &
/home/redis-2.6.17/src/redis-server --port 6382 --requirepass "test-password-123" &

/home/redis-2.8.24/src/redis-server --port 6383 &
/home/redis-2.8.24/src/redis-server --port 6384 --requirepass "test-password-123" &

/home/redis-3.0.7/src/redis-server --port 6385 &
/home/redis-3.0.7/src/redis-server --port 6386 --requirepass "test-password-123" &

/home/redis-3.2.0/src/redis-server --port 6387 --protected-mode no &
/home/redis-3.2.0/src/redis-server --port 6388 --protected-mode no --requirepass "test-password-123"

